### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by joeort** [kangarko/GameAPI#1]
Hey
can you please write a wiki about this great api.
Without any wiki and manual/introduction its very hard to develop a plugin woth this api.

**Comment by kangarko** [comment]
Yes, I am preparing a full example arena plugin.

**Comment by EazyFTW** [comment]
> Its been 9 months and I see the same thing, telling me there is an example plugin coming soon ._. Is there an ETA or is it scrapped?

Yea....

**Comment by kangarko** [comment]
Had to be scrapped due to life priorities, apologies for this.

**Comment by Fernthedev** [comment]
Ah, I understand. Thanks for the response, very helpful! Though I wish a better understanding on how to use cooldowns and correctly implementing methods like ArenaData or ArenaSettings or even the countdown system, I get that it’s not a priority. Thanks for trying at least

**Comment by kangarko** [comment]
Here is an actual implementation from CoreArena/Puncher of ArenaData: https://pastebin.com/f3KHgZfn

Much of it is custom-coded so I don't think it helps, that was another reason why documentation took so long and was scrapped.

**Comment by Fernthedev** [comment]
Thanks :) I really appreciate you answering questions on a scrapper project! Also how do you suggest I make variables work across instanced (because of events calling new instances) like for example player listing?

**Comment by kangarko** [comment]
Not really sure what you mean? Make them static? Use a singleton?

**Comment by Fernthedev** [comment]
Thanks a lot :D Hope things get better soon for you and I hope you can continue at least somewhat active development of the project later ;)

**Comment by kangarko** [comment]
GameAPI has been documented and video tutorials are in preparation as well as example plugin

**Comment by MorsikMC** [comment]
Can't wait! Coz I can't even register my arena properly ;-;

**Comment by huynhqtienvtag** [comment]
Can't wait for the tutorial

**Comment by kangarko** [comment]
mineacademy.org is in preparation, we'll prepare a complete course on coding Minecraft plugins that will also contain an entire week on minigames ;)

**Comment by JavaFactoryDev** [comment]
The GameAPI will be totally rewritten for MineAcademy. Documentation is in progress.

**Comment by kangarko** [comment]
@JavaFactoryDev Leonhard I am going to take this task myself in February 2020+ when I will record Week 6 for Project Orion in mineacademy.org :)

**Comment by DokanBoy** [comment]
Will the API be rewritten soon?

**Comment by kangarko** [comment]
We are literally recording this right now ;) However it's for students of Project Orion only, and GameAPI is already too old so we are just starting from scratch. 

I am planning to release free tutorials after we finish our training programs.

**Comment by DokanBoy** [comment]
Will the API be rewritten soon?
