### ISSUE TITLE
Method arenaPlugin#getArenas() name is ambigious. 

### ISSUE THREAD

**Issue by md5sha256** [kangarko/GameAPI#7]
The method

`#getArenas()` from the `ArenaPlugin` object is ambigious as it returns an`ArenaManager`. [here.](https://github.com/kangarko/GameAPI/blob/71d748bc129e41dcb68fb0c106f81b0871e00b61/src/main/java/org/mineacademy/gameapi/ArenaPlugin.java#L21)

This is further compounded by the fact that `ArenaManager#getArenas()` returns a `Set<Arena>`

**Comment by kangarko** [comment]
Hey,

we use a SimpleArenaManager to load and save arenas, thus return the instance of that class.

You can use ArenaRegistry#getArenaManager(yourPluginsInstance)
