### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by NQNStudios** [kangarko/GameAPI#8]
The README says this project is open-source but it is missing a `LICENSE` file and the README also says All Rights Reserved. I want to use GameAPI as part of the [MineRL](http://minerl.io/) server codebase (closed-source, for research purposes) and I need to know if we would legally be allowed to do so. Can you choose and apply an open-source license (the MIT license would be preferable) to this repository?

**Comment by kangarko** [comment]
You are allowed to use it. I have updated the README with a "Legal" section clarifying things :)
